#!/bin/sh
sudo cryptsetup open /dev/sdb1 externe
sudo mount /dev/mapper/externe /mnt/

pacman -Q | awk '{print $1}' > ~/.pkglist

SOURCES=(/root /etc /home /boot /srv)
TARGET=(/mnt/lenovo_arch)

RSYNCCONF=(--delete)

for SOURCE in "${SOURCES[@]}"
do
	sudo rsync -avP $RSYNCCONF $SOURCE $TARGET
done
