#!/bin/bash

tint2pid=`ps aux | grep tint2 | head -1 | awk '{ print $2 }'`

if [ "$tint2pid" -gt 100 ]; then
	kill -9 $tint2pid
fi

xrandr --output HDMI1 --auto --above eDP1
tint2 -c /home/mstrasser/.config/tint2/multi-monitor &
volumeicon&
