#!/bin/sh
# Starts new python TMUX session for a given project

PYTHONDIR=~/dev/python

if [ $# -eq 0 ]; then
	echo "No project name given"
	echo "usage: $0 PROJECT_NAME"
	exit 1
fi

PROJECT=$1

if [ ! -d "$PYTHONDIR/$PROJECT" ]; then
	echo "No project with that name. Existing projects: "
	ls -d $PYTHONDIR/*
	echo ""
	exit 1
fi

if [ -n $TMUX ]; then
	tmux new -c $PYTHONDIR -s $PROJECT vim $PROJECT
elif ! `tmux has-session -t $PROJECT` ; then
	echo "creating session $PROJECT"
	tmux new-session -d -c $PYTHONDIR -s $PROJECT vim $PROJECT
fi

#tmux switch-client -t $PROJECT
