#!/bin/sh
# Starts new python TMUX session for a given project

PYTHONDIR=~/dev/python

if [ $# -eq 0 ]; then
	echo "No project name given"
	echo "usage: $0 PROJECT_NAME"
	exit 1
fi

PROJECT=$1
PROJPATH="$PYTHONDIR/$PROJECT"

if [ ! -d "$PROJPATH" ]; then
	echo "No project with that name. Existing projects: "
	ls -d $PYTHONDIR/*
	echo ""
	read -p "Do you want to create $PROJECT? [Y/n]" answer

	case $answer in
		[Yy]* ) virtualenv $PROJPATH; break;;
		[Nn]* ) echo "Ok! Bye."; exit 1; break;;
		* ) virtualenv $PROJPATH; break;;
	esac
fi

if [ -n $TMUX ]; then
	tmux new -c $PROJPATH -s $PROJECT vim $PROJECT
elif ! `tmux has-session -t $PROJECT` ; then
	echo "creating session $PROJECT"
	tmux new-session -d -c $PROJPATH -s $PROJECT vim $PROJECT
fi

#tmux switch-client -t $PROJECT
